INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(100, 'SALARY1', 'EUR1', 'Maniek1', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(101, 'SALARY2', 'EUR2', 'Maniek2', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(102, 'SALARY3', 'EUR3', 'Maniek3', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(103, 'RENT', 'EUR4', 'Maniek4', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(104, 'GIFT', 'EUR5', 'Maniek5', CURRENT_TIMESTAMP);